name: 'ph_shoes_analytics'
version: '1.0.0'
config-version: 2
profile: 'ph-shoes-snowflake-connection'

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
snapshot-paths: ["snapshots"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]


target-path:   "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  ph_shoes_analytics:

    raw:
      +schema: RAW
      +materialized: view

    staging:
      +schema: STAGING
      +materialized: incremental
      +incremental_strategy: merge
      +unique_key: dwid


    marts:
      +schema: MARTS
      +materialized: table