version: 2

models:
  - name: fact_product_shoes
    description: |
      The canonical daily fact of shoe data.
      Combines BaseShoe + FactProductShoe fields and merges on (id, dwid).
      Carries forward the site‐specific `extra` JSON VARIANT for later drill‐down.
    columns:
      - name: dwid
        description: "Batch‐load date (YYYYMMDD)"
        tests:
          - not_null
          - unique

      - name: year
        description: "Batch‐load year"
        tests:
          - not_null

      - name: month
        description: "Batch‐load month"
        tests:
          - not_null

      - name: day
        description: "Batch‐load day"
        tests:
          - not_null

      - name: id
        description: "Primary product identifier"
        tests:
          - not_null

      - name: title
        description: "Product title"
        tests:
          - not_null

      - name: subTitle
        description: "Optional subtitle"

      - name: url
        description: "Product URL"
        tests:
          - not_null

      - name: image
        description: "Image URL"

      - name: price_sale
        description: "Sale price"
        tests:
          - not_null

      - name: price_original
        description: "Original list price"
        tests:
          - not_null

      - name: gender
        description: "Intended gender(s)"

      - name: age_group
        description: "Target age group"

      - name: brand
        description: "Brand name (extracted from filename)"
        tests:
          - not_null

      - name: extra
        description: |
          Site‐specific metadata for this product (VARIANT).  
          You can query any JSON keys here, e.g. `extra:colorDescription`.
