# models/staging/schema.yml
version: 2

models:
  - name: stg_product_shoes
    description: |
      Cleansed, typed staging of raw product shoes data.
      Only the core BaseShoe + FactProductShoe fields are exposed here;
      any extra brand-specific keys from the raw JSON are ignored.
    columns:
      - name: id
        description: "Primary identifier for the shoe record"
        tests:
          - not_null

      - name: title
        description: "Product title"
        tests:
          - not_null

      - name: subTitle
        description: "Optional subtitle or secondary description"

      - name: url
        description: "Product URL"
        tests:
          - not_null

      - name: image
        description: "URL to product image"

      - name: price_sale
        description: "Sale price"
        tests:
          - not_null

      - name: price_original
        description: "Original (list) price"

      - name: gender
        description: "Intended gender(s) for the shoe"
        tests:
          - not_null

      - name: age_group
        description: "Target age group, e.g. 'adult'"

      - name: brand
        description: "Brand extracted from the filename"
        tests:
          - not_null

      - name: dwid
        description: "Date-based batch load identifier (YYYYMMDD)"
        tests:
          - not_null
          - unique

      - name: year
        description: "Partition year (from dwid)"
        tests:
          - not_null

      - name: month
        description: "Partition month (from dwid)"
        tests:
          - not_null

      - name: day
        description: "Partition day (from dwid)"
        tests:
          - not_null
