version: 2

sources:
  - name: raw
    schema: RAW            
    tables:
      - name: raw_product_shoes

models:
  - name: stg_product_shoes
    description: |
      Standardized staging of product shoes data:
      - reads from RAW.RAW_PRODUCT_SHOES_RAW
      - exposes exactly the BaseShoe + FactProductShoe fields
      - adds the site-specific JSON in `extra`
      - derives dwid/year/month/day
    columns:
      - name: dwid
        description: "Batch-load date (YYYYMMDD)"
        tests:
          - not_null

      - name: year
        description: "Batch-load year"
        tests:
          - not_null

      - name: month
        description: "Batch-load month"
        tests:
          - not_null

      - name: day
        description: "Batch-load day"
        tests:
          - not_null

      - name: id
        description: "Primary product identifier"
        tests:
          - not_null

      - name: title
        description: "Product title"
        tests:
          - not_null

      - name: subTitle
        description: "Optional subtitle or secondary description"

      - name: url
        description: "Product URL"
        tests:
          - not_null

      - name: image
        description: "Product image URL"

      - name: price_sale
        description: "Sale price"
        tests:
          - not_null

      - name: price_original
        description: "Original (list) price"
        tests:
          - not_null

      - name: gender
        description: "Intended gender(s) for the shoe"
        tests:
          - not_null

      - name: age_group
        description: "Target age group (e.g. 'adult')"

      - name: brand
        description: "Brand extracted in raw landing"

      - name: extra
        description: |
          Site‐specific metadata, carried through from the extractor as JSON.
          Stored as a VARIANT so downstream models can pull out whatever keys they need.
